#!/bin/bash
#
# Cleans all test results data
#
# Data generated by test runs can become huge
# this script gets rid of all previous results.
#
##############################################

# Exit on errors.
set -e

# Dependencies.
. ./lib.sh

delete_files "$PERFORMANCE_TOOL_DIRECTORY/jmeter_data/runs/*.php"
delete_files "$PERFORMANCE_TOOL_DIRECTORY/jmeter_data/runs_samples/*.jtl"
delete_files "$PERFORMANCE_TOOL_DIRECTORY/jmeter_data/runs_outputs/*.output"
delete_files "$PERFORMANCE_TOOL_DIRECTORY/jmeter_data/logs/*.log"

# Also backups.
delete_files "$PERFORMANCE_TOOL_DIRECTORY/$backupsdir/*"

# Delete compare files.
if [ -f "$PERFORMANCE_TOOL_DIRECTORY/moodle/site_data.properties" ]; then
    delete_files "$PERFORMANCE_TOOL_DIRECTORY/moodle/site_data.properties" 1
fi

if [ -f "test_files.properties" ]; then
    delete_files "$PERFORMANCE_TOOL_DIRECTORY/test_files.properties" 1
fi

outputinfo="
#######################################################################
Runs results and backups deleted successfully.
"
echo "$outputinfo"
exit 0
